//把所有的 action 放在 constants
module.exports = {
  BOOK_CREATE: 'BOOK_CREATE',
  BOOK_UPDATE: 'BOOK_UPDATE',
  BOOK_DESTROY: 'BOOK_DESTROY',
  BOOK_DESTROY_SELECTION: 'BOOK_DESTROY_SELECTION',
  BOOK_ADD_TO_SELECTION: 'BOOK_ADD_TO_SELECTION',
  BOOK_REMOVE_FROM_SELECTION: 'BOOK_REMOVE_FROM_SELECTION',
  BOOK_RESET_SELECTION: 'BOOK_RESET_SELECTION'

  
};
