//把所有的 action 放在 constants
module.exports = {
  BOOK_CREATE: 'BOOK_CREATE',
  BOOK_DESTROY: 'BOOK_DESTROY',
  BOOK_ADD_TO_SELECTION: 'BOOK_ADD_TO_SELECTION',
  BOOK_REMOVE_FROM_SELECTION: 'BOOK_REMOVE_FROM_SELECTION',
  BOOK_MARK_SELECTION_BROUGHT: 'BOOK_MARK_SELECTION_BROUGHT',
  BOOK_MARK_SELECTION_WISH: 'BOOK_MARK_SELECTION_WISH',
  BOOK_RESET_SELECTION: 'BOOK_RESET_SELECTION'

  
};
